name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  
permissions:
  contents: "read"
  pages: "write"
  id-token: "write"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install requirements
        run: pip install pelican[markdown]
      - name: Build Pelican site
        shell: python
        run: |
          import subprocess

          cmd = "pelican content"
          cmd += " --settings publishconf.py"
          cmd += " --extra-settings"
          cmd += """ SITEURL='"${{ steps.pages.outputs.base_url }}"'"""
          cmd += """ FEED_DOMAIN='"${{ steps.pages.outputs.base_url }}"'"""
          cmd += " --output output/"
          cmd += " --theme-path themes/fiab"

          subprocess.run(cmd, shell=True, check=True)
      - name: Fix permissions
        run: |
          chmod -c -R +rX "output/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "output/"
  deploy:
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

